2024-11-01T13:25:20 exceptions must derive from BaseException
2024-11-01T13:25:20 exceptions must derive from BaseException
2024-11-01T13:25:20 '  File "quest.py", line 4818, in <module>\n    current_quest_area.complete()\n'
2024-11-01T13:25:20 '  File "quest.py", line 1225, in complete\n    raise "completed"\n'
2024-11-01T13:33:54 exceptions must derive from BaseException
2024-11-01T13:33:54 exceptions must derive from BaseException
2024-11-01T13:33:54 '  File "quest.py", line 4818, in <module>\n    current_quest_area.complete()\n'
2024-11-01T13:33:54 '  File "quest.py", line 1225, in complete\n    raise "completed"\n'
2024-11-01T13:45:05 we are stuck hard, help!
2024-11-01T13:45:06 we are stuck hard, help! , sleep 3600*24
2024-11-01T13:45:06 we are stuck hard, help! , sleep 3600*24
2024-11-01T13:45:06 '  File "quest.py", line 4818, in <module>\n    current_quest_area.complete()\n'
2024-11-01T13:45:06 '  File "quest.py", line 1130, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-11-01T13:45:06 '  File "D:\\poe_bot\\1_host\\utils\\mover.py", line 433, in goToPoint\n    poe_bot.raiseLongSleepException(\'we are stuck hard, help!\')\n'
2024-11-01T13:45:06 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 319, in raiseLongSleepException\n    raiseLongSleepException(text)\n'
2024-11-01T13:45:06 '  File "D:\\poe_bot\\1_host\\utils\\utils.py", line 108, in raiseLongSleepException\n    raise Exception(f\'{text} , sleep 3600*24\')\n'
2024-11-01T13:54:08 talk to dialla, goto other loc
2024-11-01T15:43:05 #resurrectAtCheckpoint call 1730446985.5583599
